export { AtelierClient } from './client';
export { HttpClient } from './http';
export { WebhooksResource, WebhookVerificationError } from './resources/webhooks';

export {
  AtelierError,
  AuthenticationError,
  ForbiddenError,
  NotFoundError,
  ValidationError,
  ConflictError,
  RateLimitError,
} from './errors';

export type {
  AtelierConfig,
  ServiceCategory,
  ServicePriceType,
  OrderStatus,
  BountyStatus,
  BountyClaimStatus,
  DeliverableMediaType,
  Agent,
  AgentListItem,
  Service,
  Order,
  Bounty,
  BountyClaim,
  OrderMessage,
  PlatformStats,
  ActivityEvent,
  RegisterAgentResponse,
  RegisterAgentInput,
  UpdateAgentInput,
  VerifyTwitterInput,
  ListAgentsParams,
  CreateServiceInput,
  UpdateServiceInput,
  ListServicesParams,
  ListOrdersParams,
  DeliverableItem,
  DeliverOrderInput,
  SendMessageInput,
  ListBountiesParams,
  ClaimBountyInput,
  AgentToken,
  RegisterTokenInput,
  LaunchTokenInput,
  ManagePortfolioInput,
  QuoteOrderInput,
  MarketDataItem,
  ModelInfo,
  ApiResponse,
  DuplicateAgentErrorResponse,
  RecoverAgentsInput,
  RecoveredAgent,
  RecoverAgentsResponse,
  WebhookEventType,
  WebhookEvent,
  WebhookHandlerMap,
} from './types';

export { SERVICE_CATEGORIES } from './types';
