export type SkillCategory = {
  slug: string;
  name: string;
  example: string;
  keywords: string[];
};

export const SKILL_CATEGORIES: SkillCategory[] = [
  { slug: 'medical',       name: 'Medical',       example: 'PubMed + clinical docs', keywords: ['medical', 'clinical', 'health', 'pubmed', 'drug'] },
  { slug: 'research',      name: 'Research',      example: '10h analyst run',        keywords: ['research', 'analysis', 'analyst', 'memo', 'deep dive'] },
  { slug: 'writing',       name: 'Writing',       example: 'cold email drafts',      keywords: ['writing', 'copy', 'copywriting', 'email', 'blog'] },
  { slug: 'coding',        name: 'Coding',        example: 'PR review',              keywords: ['code', 'coding', 'pr', 'review', 'refactor', 'engineering'] },
  { slug: 'design',        name: 'Design',        example: 'logo + brand kit',       keywords: ['design', 'logo', 'brand', 'figma', 'ui'] },
  { slug: 'data',          name: 'Data',          example: 'SQL queries',            keywords: ['data', 'sql', 'analytics', 'spreadsheet'] },
  { slug: 'ops',           name: 'Ops',           example: 'meeting notes',          keywords: ['ops', 'operations', 'productivity', 'tools'] },
  { slug: 'testing',       name: 'Testing',       example: 'e2e + security audit',   keywords: ['testing', 'qa', 'security', 'audit', 'verify'] },
  { slug: 'devops',        name: 'DevOps',        example: 'CI/CD pipelines',        keywords: ['devops', 'cicd', 'docker', 'kubernetes', 'cloud'] },
  { slug: 'blockchain',    name: 'Blockchain',    example: 'Solidity audit',         keywords: ['blockchain', 'solidity', 'web3', 'defi', 'nft'] },
  { slug: 'business',      name: 'Business',      example: 'investor materials',     keywords: ['business', 'finance', 'investor', 'crm'] },
  { slug: 'growth',        name: 'Growth',        example: 'SEO audit',              keywords: ['growth', 'seo', 'marketing', 'ads', 'social'] },
  { slug: 'sales',         name: 'Sales',         example: 'outbound outreach',      keywords: ['sales', 'outreach', 'outbound', 'lead'] },
  { slug: 'support',       name: 'Support',       example: 'ticket triage',          keywords: ['support', 'customer', 'ticket', 'help'] },
  { slug: 'lifestyle',     name: 'Lifestyle',     example: 'wellness + creative',    keywords: ['lifestyle', 'wellness', 'music', 'philosophy', 'art'] },
  { slug: 'other',         name: 'Other',         example: 'doesn\'t fit a category', keywords: ['other', 'misc', 'general'] },
];

export type Persona = {
  slug: string;
  name: string;
  archetype: string;
  vibe: string;
};

export const PERSONAS: Persona[] = [];

export type SkillPackId = 'medical' | 'anthropic' | 'skillsmp' | 'claudeskills' | 'community';

export type SkillPack = {
  id: SkillPackId;
  label: string;
  repoUrl: string;
  rawUrl: string;
  external?: boolean;
};

export const SKILL_PACKS: Record<SkillPackId, SkillPack> = {
  medical: {
    id: 'medical',
    label: 'OpenClaw',
    repoUrl: 'https://github.com/FreedomIntelligence/OpenClaw-Medical-Skills/tree/main/skills',
    rawUrl: 'https://raw.githubusercontent.com/FreedomIntelligence/OpenClaw-Medical-Skills/main/skills',
  },
  anthropic: {
    id: 'anthropic',
    label: 'Anthropic',
    repoUrl: 'https://github.com/anthropics/skills/tree/main/skills',
    rawUrl: 'https://raw.githubusercontent.com/anthropics/skills/main/skills',
  },
  skillsmp: {
    id: 'skillsmp',
    label: 'skillsmp',
    repoUrl: 'https://skillsmp.com',
    rawUrl: 'https://skillsmp.com/skills',
    external: true,
  },
  claudeskills: {
    id: 'claudeskills',
    label: 'claudeskills.info',
    repoUrl: 'https://claudeskills.info',
    rawUrl: 'https://claudeskills.info/skill',
    external: true,
  },
  community: {
    id: 'community',
    label: 'Community',
    repoUrl: '/skills-and-personas',
    rawUrl: '',
    external: true,
  },
};

export type SkillExample = {
  name: string;
  tagline: string;
  category: string;
  tools: string[];
  kb: string;
  price?: number;
  pack: SkillPackId;
  slug: string;
  download_url?: string;
  creator_wallet?: string;
  creator_chain?: 'solana' | 'base';
};

export function getSourceUrl(skill: SkillExample): string {
  if (skill.download_url) return skill.download_url;
  const pack = SKILL_PACKS[skill.pack];
  if (pack.external) return `${pack.rawUrl}/${encodeURIComponent(skill.slug)}`;
  return `${pack.repoUrl}/${skill.slug}`;
}

export function getDownloadUrl(skill: SkillExample): string {
  if (skill.download_url) return skill.download_url;
  const pack = SKILL_PACKS[skill.pack];
  if (pack.external) return `${pack.rawUrl}/${encodeURIComponent(skill.slug)}`;
  return `/api/skills/download?pack=${skill.pack}&slug=${encodeURIComponent(skill.slug)}`;
}

export function isExternalSkill(skill: SkillExample): boolean {
  return !!SKILL_PACKS[skill.pack].external;
}

export function getPackLabel(skill: SkillExample): string {
  return SKILL_PACKS[skill.pack].label;
}

export const MEDICAL_SKILLS: SkillExample[] = [
  {
    name: 'PubMed Search',
    tagline: 'Search the entire PubMed corpus by question, gene, or condition.',
    category: 'Medical',
    tools: ['PubMed', 'NCBI E-utils'],
    kb: '36M+ citations',
    price: 0,
    pack: 'medical',
    slug: 'pubmed-search',
  },
  {
    name: 'Biomedical Search',
    tagline: 'Unified search across PubMed, preprints, trials, and FDA labels.',
    category: 'Medical',
    tools: ['PubMed', 'ClinicalTrials.gov', 'FDA'],
    kb: 'Valyu semantic index',
    price: 0,
    pack: 'medical',
    slug: 'biomedical-search',
  },
  {
    name: 'Clinical Reports',
    tagline: 'SOAP notes, discharge summaries, CSRs. HIPAA + ICH-GCP compliant.',
    category: 'Medical',
    tools: ['CARE', 'ICH-E3'],
    kb: 'Report templates · HIPAA rules',
    price: 0,
    pack: 'medical',
    slug: 'clinical-reports',
  },
  {
    name: 'Clinical Decision Support',
    tagline: 'CDS documents with GRADE grading, biomarker integration, and stats.',
    category: 'Medical',
    tools: ['GRADE', 'hazard ratios'],
    kb: 'Treatment evidence base',
    price: 0,
    pack: 'medical',
    slug: 'clinical-decision-support',
  },
  {
    name: 'Clinical Trials Database',
    tagline: 'Query ClinicalTrials.gov by condition, drug, phase, or NCT ID.',
    category: 'Medical',
    tools: ['ClinicalTrials.gov v2'],
    kb: '500k+ trial records',
    price: 0,
    pack: 'medical',
    slug: 'clinicaltrials-database',
  },
  {
    name: 'Medical Entity Extractor',
    tagline: 'Pulls symptoms, meds, labs, and diagnoses from raw patient text.',
    category: 'Medical',
    tools: ['NER', 'ICD-10'],
    kb: 'Medical entity ontology',
    price: 0,
    pack: 'medical',
    slug: 'medical-entity-extractor',
  },
  {
    name: 'Patient-Friendly Translator',
    tagline: 'Turns letters, labs, and discharges into plain language.',
    category: 'Medical',
    tools: ['Health literacy lexicon'],
    kb: 'Patient comms templates',
    price: 0,
    pack: 'medical',
    slug: 'patiently-ai',
  },
  {
    name: 'Drug Research',
    tagline: 'Full drug profile — pharmacology, safety, trials, ADMET, PGx.',
    category: 'Medical',
    tools: ['ChEMBL', 'OpenFDA', 'PharmGKB'],
    kb: 'Drug intelligence atlas',
    price: 0,
    pack: 'medical',
    slug: 'tooluniverse-drug-research',
  },
  {
    name: 'Drug-Drug Interaction',
    tagline: 'DDI prediction, severity classification, polypharmacy analysis.',
    category: 'Medical',
    tools: ['CYP450', 'OpenFDA'],
    kb: 'Interaction mechanism map',
    price: 0,
    pack: 'medical',
    slug: 'tooluniverse-drug-drug-interaction',
  },
  {
    name: 'Clinical Guidelines',
    tagline: 'Search NICE, WHO, ADA, AHA/ACC, NCCN, CPIC for standard of care.',
    category: 'Medical',
    tools: ['NICE', 'WHO', 'ADA', 'AHA/ACC'],
    kb: '12+ guideline sources',
    price: 0,
    pack: 'medical',
    slug: 'tooluniverse-clinical-guidelines',
  },
];

export const ANTHROPIC_SKILLS: SkillExample[] = [
  {
    name: 'Algorithmic Art',
    tagline: 'Generative art in p5.js — flow fields, particles, seeded randomness.',
    category: 'Design',
    tools: ['p5.js'],
    kb: 'Generative art primitives',
    price: 0,
    pack: 'anthropic',
    slug: 'algorithmic-art',
  },
  {
    name: 'Brand Guidelines',
    tagline: "Apply Anthropic's official colors and typography to any artifact.",
    category: 'Design',
    tools: ['Brand tokens'],
    kb: 'Anthropic palette + type system',
    price: 0,
    pack: 'anthropic',
    slug: 'brand-guidelines',
  },
  {
    name: 'Canvas Design',
    tagline: 'Posters, designs, and visual art rendered to .png or .pdf.',
    category: 'Design',
    tools: ['Canvas', 'PIL'],
    kb: 'Design principles + composition',
    price: 0,
    pack: 'anthropic',
    slug: 'canvas-design',
  },
  {
    name: 'Claude API',
    tagline: 'Build, debug, and tune Claude apps. Caching, tools, model migration.',
    category: 'Coding',
    tools: ['Anthropic SDK'],
    kb: 'Prompt caching + version migration',
    price: 0,
    pack: 'anthropic',
    slug: 'claude-api',
  },
  {
    name: 'Doc Co-Authoring',
    tagline: 'Structured workflow for docs, proposals, specs, and decision memos.',
    category: 'Writing',
    tools: ['Drafting templates'],
    kb: 'Doc archetypes + review loops',
    price: 0,
    pack: 'anthropic',
    slug: 'doc-coauthoring',
  },
  {
    name: 'DOCX Toolkit',
    tagline: 'Create, read, edit .docx — TOC, headings, page numbers, tracked changes.',
    category: 'Ops',
    tools: ['python-docx'],
    kb: 'Word document spec',
    price: 0,
    pack: 'anthropic',
    slug: 'docx',
  },
  {
    name: 'Frontend Design',
    tagline: 'Production-grade React/HTML interfaces. No generic AI aesthetic.',
    category: 'Coding',
    tools: ['React', 'Tailwind', 'shadcn/ui'],
    kb: 'Frontend design archetypes',
    price: 0,
    pack: 'anthropic',
    slug: 'frontend-design',
  },
  {
    name: 'Internal Comms',
    tagline: 'Status reports, leadership updates, FAQs, incident reports in house style.',
    category: 'Writing',
    tools: ['Comms templates'],
    kb: 'Format library + voice rules',
    price: 0,
    pack: 'anthropic',
    slug: 'internal-comms',
  },
  {
    name: 'MCP Builder',
    tagline: 'Build MCP servers in Python (FastMCP) or TypeScript (MCP SDK).',
    category: 'Coding',
    tools: ['MCP SDK', 'FastMCP'],
    kb: 'Protocol spec + tool patterns',
    price: 0,
    pack: 'anthropic',
    slug: 'mcp-builder',
  },
  {
    name: 'PDF Toolkit',
    tagline: 'Read, merge, split, rotate, fill forms, OCR — full PDF stack.',
    category: 'Ops',
    tools: ['pypdf', 'PyMuPDF'],
    kb: 'PDF format reference',
    price: 0,
    pack: 'anthropic',
    slug: 'pdf',
  },
  {
    name: 'PPTX Toolkit',
    tagline: 'Build, parse, edit .pptx — slides, layouts, speaker notes.',
    category: 'Ops',
    tools: ['python-pptx'],
    kb: 'Slide layout patterns',
    price: 0,
    pack: 'anthropic',
    slug: 'pptx',
  },
  {
    name: 'Skill Creator',
    tagline: 'Author, edit, eval, and benchmark Claude skills.',
    category: 'Coding',
    tools: ['Eval harness'],
    kb: 'Skill design patterns',
    price: 0,
    pack: 'anthropic',
    slug: 'skill-creator',
  },
  {
    name: 'Slack GIF Creator',
    tagline: 'Animated GIFs sized, looped, and validated for Slack.',
    category: 'Design',
    tools: ['ffmpeg', 'PIL'],
    kb: 'Slack GIF constraints',
    price: 0,
    pack: 'anthropic',
    slug: 'slack-gif-creator',
  },
  {
    name: 'Theme Factory',
    tagline: 'Apply 10 preset themes to artifacts, or generate one on the fly.',
    category: 'Design',
    tools: ['Theme tokens'],
    kb: '10 preset themes',
    price: 0,
    pack: 'anthropic',
    slug: 'theme-factory',
  },
  {
    name: 'Web Artifacts',
    tagline: 'Multi-component React + shadcn artifacts with routing and state.',
    category: 'Coding',
    tools: ['React', 'Tailwind', 'shadcn/ui'],
    kb: 'Artifact composition patterns',
    price: 0,
    pack: 'anthropic',
    slug: 'web-artifacts-builder',
  },
  {
    name: 'Webapp Testing',
    tagline: 'Playwright toolkit — screenshots, logs, UI behavior checks.',
    category: 'Coding',
    tools: ['Playwright'],
    kb: 'Testing patterns + selectors',
    price: 0,
    pack: 'anthropic',
    slug: 'webapp-testing',
  },
  {
    name: 'XLSX Toolkit',
    tagline: 'Open, edit, fix, create spreadsheets. Formulas, charts, cleanup.',
    category: 'Data',
    tools: ['openpyxl', 'pandas'],
    kb: 'xlsx format + cleanup patterns',
    price: 0,
    pack: 'anthropic',
    slug: 'xlsx',
  },
];

function ssmp(
  name: string,
  tagline: string,
  category: string,
  tools: string[],
  slug: string,
  kb = 'skillsmp.com',
): SkillExample {
  return { name, tagline, category, tools, kb, price: 0, pack: 'skillsmp', slug };
}

export const SKILLSMP_SKILLS: SkillExample[] = [
  // ── Tools / Ops ──────────────────────────────────────────────────────────
  ssmp('Clawsweeper', 'OpenClaw issue/PR sweep reports, commit reviews, repair jobs, cloud fixes, and GitHub Actions monitoring.', 'Ops', ['github', 'openclaw', 'automation'], 'openclaw-openclaw-agents-skills-clawsweeper-skill-md'),
  ssmp('Gitcrawl', 'Archive search, duplicate discovery, thread clustering, and GitHub mirror freshness checks.', 'Ops', ['github', 'search', 'openclaw'], 'openclaw-openclaw-agents-skills-gitcrawl-skill-md'),
  ssmp('OpenClaw QA Testing', 'Run, watch, debug, and explain OpenClaw qa-lab and qa-channel scenarios.', 'Testing', ['openclaw', 'qa'], 'openclaw-openclaw-agents-skills-openclaw-qa-testing-skill-md'),
  ssmp('Secret Scanning Maintainer', 'Triage, redact, and resolve GitHub Secret Scanning alerts.', 'Testing', ['security', 'github', 'openclaw'], 'openclaw-openclaw-agents-skills-openclaw-secret-scanning-maintainer-skill-md'),
  ssmp('Test Heap Leaks', 'Investigate memory growth, Vitest OOMs, and RSS spikes.', 'Testing', ['vitest', 'performance', 'memory'], 'openclaw-openclaw-agents-skills-openclaw-test-heap-leaks-skill-md'),
  ssmp('Test Performance', 'Benchmark and optimize test runtime, CPU/RSS, heap growth.', 'Testing', ['performance', 'benchmarking'], 'openclaw-openclaw-agents-skills-openclaw-test-performance-skill-md'),
  ssmp('Parallels Discord Roundtrip', 'macOS Parallels smoke testing with Discord send and verification.', 'Testing', ['parallels', 'discord', 'macos'], 'openclaw-openclaw-agents-skills-parallels-discord-roundtrip-skill-md'),
  ssmp('Telegram Crabbox E2E Proof', 'Control Telegram Desktop with TDLib, WebVNC observation, and artifact recording.', 'Testing', ['telegram', 'tdlib', 'e2e'], 'openclaw-openclaw-agents-skills-telegram-crabbox-e2e-proof-skill-md'),
  ssmp('Browser Automation', 'Control web pages, multi-step flows, login checks, and tab management.', 'Ops', ['browser', 'automation', 'web'], 'openclaw-openclaw-extensions-browser-skills-browser-automation-skill-md'),
  ssmp('Feishu Doc', 'Read/write operations for Feishu documents and cloud docs.', 'Ops', ['feishu', 'docs'], 'openclaw-openclaw-extensions-feishu-skills-feishu-doc-skill-md'),
  ssmp('Feishu Drive', 'Feishu cloud storage and file management.', 'Ops', ['feishu', 'storage'], 'openclaw-openclaw-extensions-feishu-skills-feishu-drive-skill-md'),
  ssmp('Feishu Wiki', 'Feishu knowledge base navigation.', 'Writing', ['feishu', 'wiki'], 'openclaw-openclaw-extensions-feishu-skills-feishu-wiki-skill-md'),
  ssmp('OpenProse', 'OpenProse VM skill pack orchestrating multi-agent workflows.', 'Ops', ['orchestration', 'workflows'], 'openclaw-openclaw-extensions-open-prose-skills-prose-skill-md'),
  ssmp('QQBot Channel', 'QQ channel management, guilds, posts, announcements, schedules.', 'Ops', ['qq', 'messaging'], 'openclaw-openclaw-extensions-qqbot-skills-qqbot-channel-skill-md'),
  ssmp('QQBot Reminders', 'Create and manage one-time or recurring QQ reminders.', 'Ops', ['qq', 'reminders'], 'openclaw-openclaw-extensions-qqbot-skills-qqbot-remind-skill-md'),
  ssmp('Apple Notes', 'Create, view, edit, search, and export Apple Notes on macOS.', 'Ops', ['apple', 'notes', 'macos'], 'openclaw-openclaw-skills-apple-notes-skill-md'),
  ssmp('Apple Reminders', 'List, add, edit, complete Apple Reminders and reminder lists.', 'Ops', ['apple', 'macos'], 'openclaw-openclaw-skills-apple-reminders-skill-md'),
  ssmp('Bear Notes', 'Create, search, and manage Bear notes via grizzly CLI.', 'Ops', ['notes', 'macos'], 'openclaw-openclaw-skills-bear-notes-skill-md'),
  ssmp('Blogwatcher', 'Monitor blogs and RSS/Atom feeds for updates.', 'Ops', ['rss', 'monitoring'], 'openclaw-openclaw-skills-blogwatcher-skill-md'),
  ssmp('BluOS CLI', 'BluOS speaker discovery, playback, grouping, and volume control.', 'Ops', ['audio', 'iot'], 'openclaw-openclaw-skills-blucli-skill-md'),
  ssmp('ClawHub', 'Search, install, update, and publish agent skills via registry.', 'Coding', ['cli', 'registry'], 'openclaw-openclaw-skills-clawhub-skill-md'),
  ssmp('Coding Agent', 'Delegate coding tasks to Codex, Claude Code, or other agents for features, refactoring, and PR reviews.', 'Coding', ['claude', 'codex', 'agents'], 'openclaw-openclaw-skills-coding-agent-skill-md'),
  ssmp('Discord', 'React, pin/unpin, send, edit, delete Discord messages.', 'Ops', ['discord', 'messaging'], 'openclaw-openclaw-skills-discord-skill-md'),
  ssmp('EightSleep Control', 'Control Eight Sleep pods for status, temperature, alarms, schedules.', 'Lifestyle', ['smart-home', 'iot'], 'openclaw-openclaw-skills-eightctl-skill-md'),
  ssmp('Gemini', 'Gemini CLI for Q&A, summaries, and content generation.', 'Coding', ['google', 'llm'], 'openclaw-openclaw-skills-gemini-skill-md'),
  ssmp('Google Workspace', 'Gmail, Calendar, Drive, Contacts, Sheets, and Docs integration.', 'Ops', ['google', 'workspace'], 'openclaw-openclaw-skills-gog-skill-md'),
  ssmp('Healthcheck', 'Audit hosts for SSH, firewall, updates, exposure, and risk posture.', 'Testing', ['security', 'devops'], 'openclaw-openclaw-skills-healthcheck-skill-md'),
  ssmp('Himalaya', 'List, read, search, compose, and organize IMAP/SMTP email.', 'Ops', ['email', 'imap'], 'openclaw-openclaw-skills-himalaya-skill-md'),
  ssmp('iMessage', 'List chats, retrieve history, send iMessage/SMS via Messages.app.', 'Ops', ['messaging', 'macos'], 'openclaw-openclaw-skills-imsg-skill-md'),
  ssmp('Notion', 'Notion API for pages, databases, and content blocks management.', 'Ops', ['notion', 'productivity'], 'openclaw-openclaw-skills-notion-skill-md'),
  ssmp('Slack', 'React, pin/unpin, send, edit, delete Slack messages; fetch member info.', 'Ops', ['slack', 'messaging'], 'openclaw-openclaw-skills-slack-skill-md'),

  // ── Business ─────────────────────────────────────────────────────────────
  ssmp('Ordercli', 'Foodora-only CLI for checking past orders and active order status.', 'Business', ['foodora', 'cli'], 'ordercli'),
  ssmp('Taskflow Inbox Triage', 'TaskFlow pattern for inbox triage, intent routing, waiting on replies.', 'Business', ['email', 'tasks'], 'taskflow-inbox-triage'),
  ssmp('Things Mac', 'Add, update, list, search, or inspect Things 3 todos on macOS.', 'Business', ['macos', 'tasks'], 'things-mac'),
  ssmp('Trello', 'Manage Trello boards, lists, and cards via the Trello REST API.', 'Business', ['trello', 'pm'], 'trello'),
  ssmp('Weather', 'Get current weather, rain, temperature, and forecasts for locations.', 'Business', ['weather'], 'weather'),
  ssmp('Investor Materials', 'Create pitch decks, one-pagers, memos, and fundraising documents.', 'Business', ['fundraising'], 'investor-materials'),
  ssmp('Investor Outreach', 'Draft cold emails and personalized investor communications.', 'Business', ['fundraising', 'email'], 'investor-outreach'),
  ssmp('Market Research', 'Conduct competitive analysis and industry intelligence research.', 'Research', ['competitive', 'strategy'], 'market-research'),
  ssmp('Energy Procurement', 'Electricity and gas procurement, tariff optimization, hedging strategies.', 'Business', ['energy', 'procurement'], 'energy-procurement'),
  ssmp('Logistics Exception Management', 'Handle freight exceptions, damages, losses, and carrier disputes.', 'Business', ['logistics', 'supply-chain'], 'logistics-exception-management'),
  ssmp('Returns Reverse Logistics', 'Return authorization, inspection, disposal, and refund workflows.', 'Business', ['returns', 'supply-chain'], 'returns-reverse-logistics'),
  ssmp('Carrier Relationship Management', 'Manage carrier portfolios, negotiate rates, track performance.', 'Business', ['logistics', 'procurement'], 'carrier-relationship-management'),
  ssmp('Connections Optimizer', 'Reorganize X and LinkedIn networks with pruning and outreach.', 'Sales', ['social', 'networking'], 'connections-optimizer'),
  ssmp('Customer Billing Ops', 'Operate subscription, refunds, churn triage via Stripe integration.', 'Business', ['stripe', 'billing'], 'customer-billing-ops'),
  ssmp('Customs Trade Compliance', 'Tariff classification, duty optimization, import/export documentation.', 'Business', ['trade', 'compliance'], 'customs-trade-compliance'),
  ssmp('Finance Billing Ops', 'Revenue, pricing, refunds, and billing-model workflows.', 'Business', ['finance', 'billing'], 'finance-billing-ops'),
  ssmp('Healthcare EMR Patterns', 'EMR/EHR development with clinical safety and workflows.', 'Medical', ['emr', 'ehr'], 'healthcare-emr-patterns'),
  ssmp('Inventory Demand Planning', 'Demand forecasting, safety stock optimization, replenishment.', 'Business', ['supply-chain'], 'inventory-demand-planning'),
  ssmp('Jira Integration', 'Retrieve tickets, analyze requirements, update issue status.', 'Business', ['jira', 'pm'], 'jira-integration'),
  ssmp('Dashboard Builder', 'Build monitoring dashboards for Grafana and SigNoz.', 'DevOps', ['grafana', 'monitoring'], 'dashboard-builder'),

  // ── Development / Coding ────────────────────────────────────────────────
  ssmp('ACP Router', 'Route plain-language requests for Pi, Claude Code, Cursor, Copilot, and other agents.', 'Coding', ['agents', 'routing'], 'acp-router'),
  ssmp('Xurl', 'X API for posts, replies, search, DMs, and media uploads.', 'Ops', ['x', 'twitter'], 'xurl'),
  ssmp('Dispatching Parallel Agents', 'Use when facing 2+ independent tasks without shared state.', 'Coding', ['agents', 'parallel'], 'dispatching-parallel-agents'),
  ssmp('Create Prompt', 'Reusable prompt files for common development tasks.', 'Coding', ['prompts', 'vscode'], 'create-prompt'),
  ssmp('Project Setup Info', 'Comprehensive setup steps for full project initialization.', 'Coding', ['scaffolding'], 'project-setup-info-context7'),
  ssmp('Sessions', 'Agents window architecture and development guidelines.', 'Coding', ['vscode', 'architecture'], 'sessions'),
  ssmp('Kotlin Coroutines & Flows', 'Kotlin async patterns for Android and KMP development.', 'Coding', ['kotlin', 'android'], 'kotlin-coroutines-flows'),
  ssmp('Kotlin Patterns', 'Idiomatic Kotlin patterns for building robust applications.', 'Coding', ['kotlin'], 'kotlin-patterns'),
  ssmp('Laravel Patterns', 'Laravel architecture, routing, Eloquent ORM, and APIs.', 'Coding', ['laravel', 'php'], 'laravel-patterns'),
  ssmp('Golang Patterns', 'Idiomatic Go patterns for building robust applications.', 'Coding', ['go'], 'golang-patterns'),
  ssmp('Liquid Glass Design', 'iOS 26 liquid glass design system for SwiftUI and UIKit.', 'Design', ['swiftui', 'ios'], 'liquid-glass-design'),
  ssmp('API Design', 'REST API patterns including naming, status codes, pagination.', 'Coding', ['rest', 'api'], 'api-design'),
  ssmp('Backend Patterns', 'Backend architecture patterns for Node.js, Express, Next.js.', 'Coding', ['nodejs', 'express'], 'backend-patterns'),
  ssmp('Bun Runtime', 'Bun as runtime, package manager, bundler, and test runner.', 'Coding', ['bun', 'js'], 'bun-runtime'),
  ssmp('Coding Standards', 'Baseline cross-project coding conventions for naming and readability.', 'Coding', ['standards'], 'coding-standards'),
  ssmp('Documentation Lookup', 'Use up-to-date library and framework docs via Context7 MCP.', 'Coding', ['context7', 'mcp'], 'documentation-lookup'),
  ssmp('Frontend Patterns', 'Frontend patterns for React, Next.js, and state management.', 'Coding', ['react', 'nextjs'], 'frontend-patterns'),
  ssmp('MCP Server Patterns', 'Build MCP servers with Node/TypeScript SDK.', 'Coding', ['mcp', 'typescript'], 'mcp-server-patterns'),
  ssmp('Next.js Turbopack', 'Next.js 16+ and Turbopack — incremental bundling, FS caching.', 'Coding', ['nextjs', 'turbopack'], 'nextjs-turbopack'),
  ssmp('Product Capability', 'Translate PRD intent into implementation-ready capability plan.', 'Coding', ['product', 'planning'], 'product-capability'),
  ssmp('Java Coding Standards', 'Spring Boot coding standards for naming and architecture.', 'Coding', ['java', 'spring'], 'java-coding-standards'),
  ssmp('Django Patterns', 'Django architecture patterns, REST API design, ORM best practices.', 'Coding', ['django', 'python'], 'django-patterns'),

  // ── Data & AI ───────────────────────────────────────────────────────────
  ssmp('Model Usage', 'Summarize cost logs by model for Codex or Claude.', 'Data', ['analytics', 'cost'], 'openclaw-openclaw-skills-model-usage-skill-md'),
  ssmp('OpenAI Whisper API', 'Transcribe audio via OpenAI Audio Transcriptions API.', 'Data', ['openai', 'whisper'], 'openclaw-openclaw-skills-openai-whisper-api-skill-md'),
  ssmp('OpenAI Whisper', 'Local speech-to-text with Whisper CLI (no API key).', 'Data', ['whisper', 'offline'], 'openclaw-openclaw-skills-openai-whisper-skill-md'),
  ssmp('Sag', 'ElevenLabs text-to-speech with mac-style say UX.', 'Data', ['elevenlabs', 'tts'], 'openclaw-openclaw-skills-sag-skill-md'),
  ssmp('Sherpa ONNX TTS', 'Local text-to-speech via sherpa-onnx (offline, no cloud).', 'Data', ['tts', 'onnx'], 'openclaw-openclaw-skills-sherpa-onnx-tts-skill-md'),
  ssmp('Skill Creator', 'Create, edit, improve, review, audit agent skills.', 'Coding', ['skills'], 'openclaw-openclaw-skills-skill-creator-skill-md'),
  ssmp('Voice Call', 'Start voice calls via OpenClaw voice-call plugin.', 'Ops', ['voice'], 'openclaw-openclaw-skills-voice-call-skill-md'),
  ssmp('Create Agent', 'Create a custom agent for a specific job.', 'Coding', ['vscode', 'agents'], 'microsoft-vscode-extensions-copilot-assets-prompts-skills-create-agent-skill-md'),
  ssmp('Create Hook', 'Create hooks to enforce policy or automate lifecycle events.', 'Coding', ['vscode', 'hooks'], 'microsoft-vscode-extensions-copilot-assets-prompts-skills-create-hook-skill-md'),
  ssmp('Iterative Retrieval', 'Progressive context retrieval refinement for sub-agent problems.', 'Data', ['rag', 'agents'], 'affaan-m-everything-claude-code-docs-zh-cn-skills-iterative-retrieval-skill-md'),
  ssmp('Agent Introspection Debugging', 'Structured self-debugging for AI agent failures.', 'Testing', ['debugging', 'observability'], 'affaan-m-everything-claude-code-agents-skills-agent-introspection-debugging-skill-md'),
  ssmp('Crosspost', 'Multi-platform content distribution across X, LinkedIn, Threads, Bluesky.', 'Growth', ['social'], 'affaan-m-everything-claude-code-agents-skills-crosspost-skill-md'),
  ssmp('DMux Workflows', 'Multi-agent orchestration using tmux pane manager.', 'Coding', ['tmux', 'agents'], 'affaan-m-everything-claude-code-agents-skills-dmux-workflows-skill-md'),
  ssmp('ClickHouse IO', 'Database patterns, query optimization, analytics for high-performance workloads.', 'Data', ['clickhouse'], 'affaan-m-everything-claude-code-skills-clickhouse-io-skill-md'),
  ssmp('Continuous Learning', 'Extract reusable patterns from sessions and save as learned skills.', 'Coding', ['learning'], 'affaan-m-everything-claude-code-skills-continuous-learning-skill-md'),
  ssmp('Agent Harness Construction', 'Design and optimize AI agent action spaces and tool definitions.', 'Coding', ['agents'], 'affaan-m-everything-claude-code-skills-agent-harness-construction-skill-md'),
  ssmp('AI-First Engineering', 'Engineering model where AI agents generate significant implementation.', 'Coding', ['agents'], 'affaan-m-everything-claude-code-skills-ai-first-engineering-skill-md'),
  ssmp('Blueprint', 'Transform objectives into step-by-step multi-session project plans.', 'Coding', ['planning'], 'affaan-m-everything-claude-code-skills-blueprint-skill-md'),
  ssmp('Claude DevFleet', 'Orchestrate multi-agent coding with planning and progress monitoring.', 'Coding', ['agents'], 'affaan-m-everything-claude-code-skills-claude-devfleet-skill-md'),
  ssmp('Content Hash Cache', 'Cache file processing using SHA-256 with auto-invalidation.', 'Coding', ['caching'], 'affaan-m-everything-claude-code-skills-content-hash-cache-pattern-skill-md'),
  ssmp('Cost-Aware LLM Pipeline', 'Cost optimization for LLM API usage with model routing.', 'Data', ['llm', 'devops'], 'cost-aware-llm-pipeline'),

  // ── DevOps ──────────────────────────────────────────────────────────────
  ssmp('Crabbox', 'OpenClaw remote Linux validation on AWS and Hetzner.', 'DevOps', ['linux', 'aws'], 'crabbox'),
  ssmp('GHSA Maintainer', 'Manage OpenClaw security advisories and patch validation.', 'Testing', ['security', 'github'], 'openclaw-ghsa-maintainer'),
  ssmp('Parallels Smoke', 'Run, rerun, debug, or interpret OpenClaw Parallels test checks.', 'Testing', ['parallels'], 'openclaw-parallels-smoke'),
  ssmp('Pre-Release Plugin Testing', 'Validate pre-release plugins across bundled artifacts and E2E tests.', 'Testing', ['e2e', 'docker'], 'openclaw-pre-release-plugin-testing'),
  ssmp('OpenClaw Testing', 'Choose, run, rerun, or debug OpenClaw tests and CI checks.', 'Testing', ['ci', 'docker'], 'openclaw-testing'),
  ssmp('OptimizeTests', 'Optimize slow tests and reduce CI wall time without dropping coverage.', 'Testing', ['ci', 'performance'], 'optimizetests'),
  ssmp('Security Triage', 'Triage OpenClaw security advisories, drafts, and GHSA reports.', 'Testing', ['security'], 'security-triage'),
  ssmp('Tag Duplicate PRs', 'Search and group duplicate GitHub issues and PRs.', 'DevOps', ['github'], 'tag-duplicate-prs-issues'),
  ssmp('GitHub', 'Use gh for GitHub issues, PR status, CI/logs, comments, reviews.', 'DevOps', ['github', 'cli'], 'github'),
  ssmp('GH Issues', 'Fetch GitHub issues, delegate fixes to subagents, open PRs.', 'DevOps', ['github'], 'gh-issues'),
  ssmp('Executing Plans', 'Execute implementation plans in separate sessions with checkpoints.', 'Coding', ['planning'], 'executing-plans'),
  ssmp('Subagent-Driven Development', 'Execute implementation with independent parallel tasks.', 'Coding', ['agents'], 'subagent-driven-development-skill'),
  ssmp('Using Git Worktrees', 'Isolate feature work via git worktrees for parallel development.', 'DevOps', ['git'], 'using-git-worktrees'),
  ssmp('Writing Skills', 'Create, edit, and verify new agent skills before deployment.', 'Coding', ['skills'], 'writing-skills'),
  ssmp('Azure Pipelines', 'Validate Azure DevOps pipeline changes for the VS Code build.', 'DevOps', ['azure', 'ci'], 'azure-pipelines'),
  ssmp('OpenTelemetry', 'OpenTelemetry instrumentation for the Copilot Chat extension.', 'DevOps', ['otel', 'observability'], 'otel'),
  ssmp('Deployment Patterns', 'CI/CD pipeline patterns, Docker containerization, rollback strategies.', 'DevOps', ['docker', 'cicd'], 'deployment-patterns'),
  ssmp('GitHub Ops', 'GitHub repository operations, automation, and management.', 'DevOps', ['github'], 'github-ops'),
  ssmp('Cloudflare', 'Cloudflare Workers, Pages, AI, and platform operations.', 'DevOps', ['cloudflare'], 'cloudflare'),
  ssmp('Modal Serverless GPU', 'Serverless GPU cloud platform for running ML workloads.', 'DevOps', ['gpu', 'mlops'], 'modal-serverless-gpu'),

  // ── Testing & Security ──────────────────────────────────────────────────
  ssmp('1Password', 'Set up and use 1Password CLI for sign-in, desktop integration, secrets.', 'Testing', ['1password', 'secrets'], '1password'),
  ssmp('Feature Flags', 'Use when feature flag tests fail or need updating in React.', 'Testing', ['react', 'flags'], 'feature-flags'),
  ssmp('Fix', 'Use when you have lint errors, formatting issues, or before committing code.', 'Coding', ['lint'], 'fix'),
  ssmp('Flow', 'Run Flow type checking, or address Flow type errors.', 'Testing', ['flow', 'types'], 'flow'),
  ssmp('Test', 'Run tests for React core.', 'Testing', ['react'], 'test'),
  ssmp('Verify', 'Validate changes before committing.', 'Testing', ['react', 'ci'], 'verify'),
  ssmp('Receiving Code Review', 'Use when receiving code review feedback before implementing suggestions.', 'Coding', ['review'], 'receiving-code-review'),
  ssmp('Requesting Code Review', 'Use when completing tasks, implementing major features, or before merging.', 'Coding', ['review'], 'requesting-code-review'),
  ssmp('Test-Driven Development', 'Use when implementing any feature or bugfix, before writing implementation.', 'Testing', ['tdd'], 'test-driven-development'),
  ssmp('Verification Before Completion', 'Run verification commands and confirm output before success.', 'Testing', ['verification'], 'verification-before-completion'),
  ssmp('Writing Plans', 'Use when you have a spec or requirements for a multi-step task.', 'Coding', ['planning'], 'writing-plans'),
  ssmp('Add Policy', 'Adding, modifying, or reviewing VS Code configuration policies.', 'Coding', ['vscode'], 'add-policy'),
  ssmp('Hygiene', 'Pre-commit hooks, unicode restrictions, and formatting rules.', 'Coding', ['lint'], 'hygiene'),
  ssmp('Integration Tests', 'Running integration tests in the VS Code repo.', 'Testing', ['vscode'], 'integration-tests'),
  ssmp('Unit Tests', 'Running unit tests in the VS Code repo.', 'Testing', ['vscode'], 'unit-tests'),
  ssmp('Write Frontend Tests', 'Plan integration tests for changed frontend pages and write them.', 'Testing', ['frontend'], 'write-frontend-tests'),
  ssmp('Kotlin Testing', 'Use Kotest, MockK, coroutine testing, and property-based testing.', 'Testing', ['kotlin'], 'kotlin-testing'),
  ssmp('Laravel Security', 'Laravel security best practices covering authentication and authorization.', 'Testing', ['laravel', 'security'], 'laravel-security'),
  ssmp('Laravel TDD', 'Use PHPUnit and Pest, factories, database testing, and mocking.', 'Testing', ['laravel', 'tdd'], 'laravel-tdd'),
  ssmp('Go Testing', 'Go testing patterns including table-driven tests, subtests, and benchmarks.', 'Testing', ['go'], 'golang-testing'),
  ssmp('Laravel Verification', 'Verification loop: env checks, linting, static analysis, security scans.', 'Testing', ['laravel'], 'laravel-verification'),
  ssmp('E2E Testing', 'Playwright E2E testing patterns, Page Object Model, and CI/CD integration.', 'Testing', ['playwright', 'e2e'], 'e2e-testing'),
  ssmp('Eval Harness', 'Formal evaluation framework implementing eval-driven development.', 'Testing', ['evals'], 'eval-harness'),
  ssmp('Security Review', 'Use when adding authentication, handling user input, or working with secrets.', 'Testing', ['security'], 'security-review'),

  // ── Content & Media ─────────────────────────────────────────────────────
  ssmp('Diffs', 'Produce real, shareable diffs (viewer URL, file artifact, or both).', 'Coding', ['diff'], 'diffs'),
  ssmp('Qqbot Media', 'Send image, voice, video, or file attachments via QQBot.', 'Design', ['qq', 'media'], 'qqbot-media'),
  ssmp('Camsnap', 'Capture frames or clips from RTSP/ONVIF cameras.', 'Design', ['camera', 'rtsp'], 'camsnap'),
  ssmp('Gifgrep', 'Search GIF providers, download results, extract stills/sheets.', 'Design', ['gif'], 'gifgrep'),
  ssmp('Nano PDF', 'Edit PDFs with natural-language instructions via CLI.', 'Ops', ['pdf'], 'nano-pdf'),
  ssmp('Songsee', 'Generate spectrograms and feature visualizations from audio.', 'Design', ['audio', 'visualization'], 'songsee'),
  ssmp('Summarize', 'Summarize/transcribe URLs, videos, podcasts, PDFs, files.', 'Writing', ['summarize'], 'summarize'),
  ssmp('Video Frames', 'Extract frames or short clips from videos using ffmpeg.', 'Design', ['ffmpeg', 'video'], 'video-frames'),
  ssmp('Loom Transcript', 'Fetch and display full transcript from Loom video URLs.', 'Writing', ['loom'], 'n8n-loom-transcript'),
  ssmp('Frontend Slides', 'Create animation-rich HTML presentations or convert PowerPoint.', 'Design', ['presentations'], 'frontend-slides'),
  ssmp('Article Writing', 'Write long-form content with distinctive voice and brand consistency.', 'Writing', ['content'], 'article-writing'),
  ssmp('Brand Voice', 'Build writing style profiles from real examples, reuse across workflows.', 'Writing', ['brand'], 'brand-voice'),
  ssmp('Content Engine', 'Create platform-native content for X, LinkedIn, TikTok, YouTube.', 'Growth', ['social'], 'content-engine'),
  ssmp('Fal AI Media', 'Text-to-image, text/image-to-video, text-to-speech, video-to-audio.', 'Design', ['fal', 'ai'], 'fal-ai-media'),
  ssmp('Video Editing', 'AI-assisted workflows for cutting, structuring, augmenting footage.', 'Design', ['ffmpeg', 'video'], 'video-editing'),
  ssmp('Nutrient Document Processing', 'Process, convert, OCR, extract, redact, sign, fill documents.', 'Ops', ['pdf', 'ocr'], 'nutrient-document-processing'),
  ssmp('Concept Diagrams', 'Generate flat SVG diagrams with educational visual language.', 'Design', ['svg'], 'concept-diagrams'),
  ssmp('Hyperframes', 'Create HTML video compositions, animated cards, audio-reactive visuals.', 'Design', ['html', 'video'], 'hyperframes'),
  ssmp('Meme Generation', 'Generate real meme images by picking templates and overlaying text.', 'Design', ['memes'], 'meme-generation'),
  ssmp('Architecture Diagram', 'Dark-themed SVG architecture/cloud/infra diagrams as HTML.', 'Design', ['svg', 'diagrams'], 'architecture-diagram'),
  ssmp('ASCII Art', 'Create ASCII art using pyfiglet, cowsay, boxes, image conversion.', 'Design', ['ascii'], 'ascii-art'),
  ssmp('ASCII Video', 'Convert video/audio to colored ASCII MP4/GIF format.', 'Design', ['ascii', 'video'], 'ascii-video'),
  ssmp('Baoyu Infographic', '21 layouts × 21 styles for data visualization infographics.', 'Design', ['infographics'], 'baoyu-infographic'),
  ssmp('Design MD', 'Author, validate, export Google DESIGN.md token spec files.', 'Design', ['design-systems'], 'design-md'),
  ssmp('Visa Doc Translate', 'Translate visa documents (images) to English, create bilingual PDF.', 'Writing', ['translation'], 'visa-doc-translate'),
  ssmp('VideoDb', 'See, understand, act on video/audio with indexing and timeline edits.', 'Design', ['video'], 'videodb'),
  ssmp('Book Translation', 'Translate book chapters and UI strings to new languages.', 'Writing', ['translation'], 'book-translation'),
  ssmp('Regex vs LLM', 'Decision framework for choosing regex vs LLM for text parsing.', 'Coding', ['regex'], 'regex-vs-llm-structured-text'),

  // ── Documentation / Writing ─────────────────────────────────────────────
  ssmp('OpenClaw Docs', 'Write or review high-quality OpenClaw developer documentation.', 'Writing', ['docs'], 'openclaw-docs'),
  ssmp('Obsidian Vault Maintainer', 'Maintain wiki vaults with wikilinks and frontmatter support.', 'Writing', ['obsidian'], 'obsidian-vault-maintainer'),
  ssmp('Wiki Maintainer', 'OpenClaw memory wiki management with deterministic pages.', 'Writing', ['wiki'], 'wiki-maintainer'),
  ssmp('Tavily', 'Web search, content extraction, and research tools.', 'Research', ['tavily', 'search'], 'tavily'),
  ssmp('Create Instructions', 'Generate .instructions.md project convention files.', 'Writing', ['conventions'], 'create-instructions'),
  ssmp('Init', 'Generate chat customization files for AI coding agents.', 'Coding', ['agents'], 'init'),
  ssmp('Update Skills', 'Capture and update repository skills from session learnings.', 'Coding', ['skills'], 'update-skills'),
  ssmp('Codebase Onboarding', 'Structured guides for unfamiliar codebases with architecture maps.', 'Writing', ['onboarding'], 'codebase-onboarding'),
  ssmp('Code Tour', 'Create CodeTour .tour files for architecture walkthroughs.', 'Writing', ['vscode'], 'code-tour'),
  ssmp('Write API Reference', 'Produce API reference documentation with examples.', 'Writing', ['api-docs'], 'write-api-reference'),
  ssmp('Write Guide', 'Generate technical guides with progressive step-by-step examples.', 'Writing', ['guides'], 'write-guide'),
  ssmp('Doc Coauthoring', 'Structured workflow for collaborative documentation writing.', 'Writing', ['docs'], 'doc-coauthoring'),
  ssmp('Technical Writer', 'Clear documentation, APIs, guides, and technical content creation.', 'Writing', ['technical'], 'technical-writer'),
  ssmp('Deep Research', 'Comprehensive research synthesis from multiple sources with citations.', 'Research', ['research'], 'deep-research'),
  ssmp('Python Expert', 'Senior Python development guidance and code review.', 'Coding', ['python'], 'python-expert'),
  ssmp('Docker Management', 'Docker container, image, and Compose stack operations.', 'DevOps', ['docker'], 'docker-management'),

  // ── Research ─────────────────────────────────────────────────────────────
  ssmp('Goplaces', 'Query Google Places for text search, place details, reviews, JSON.', 'Research', ['google-places'], 'goplaces'),
  ssmp('Automation Audit Ops', 'Inventory and overlap audit workflow for jobs, hooks, MCP servers.', 'Ops', ['mcp', 'audit'], 'automation-audit-ops'),
  ssmp('Healthcare CDSS Patterns', 'Clinical Decision Support System patterns and drug interaction checking.', 'Medical', ['cdss', 'emr'], 'healthcare-cdss-patterns'),
  ssmp('Research Ops', 'Evidence-first workflow for gathering facts, comparisons, recommendations.', 'Research', ['evidence'], 'research-ops'),
  ssmp('Qdrant Vector Search', 'High-performance vector similarity search engine for RAG and semantic search.', 'Data', ['qdrant', 'rag'], 'qdrant-vector-search'),
  ssmp('Sparse Autoencoder Training', 'Train SAEs to decompose neural network activations into features.', 'Data', ['ml', 'interpretability'], 'sparse-autoencoder-training'),
  ssmp('Bioinformatics', 'Gateway to 400+ bioinformatics skills covering genomics and variant calling.', 'Medical', ['genomics'], 'bioinformatics'),
  ssmp('Drug Discovery', 'Search bioactive compounds, calculate drug-likeness, drug interactions.', 'Medical', ['chembl', 'openfda'], 'drug-discovery'),
  ssmp('Qmd', 'Search personal knowledge bases using hybrid retrieval with BM25 and vector search.', 'Research', ['rag', 'kb'], 'qmd'),
  ssmp('LM Evaluation Harness', 'Benchmark LLMs on MMLU, GSM8K, and other benchmarks.', 'Data', ['evals'], 'evaluating-llms-harness'),
  ssmp('Weights & Biases', 'Log ML experiments, sweeps, model registry, dashboards.', 'Data', ['mlops'], 'weights-and-biases'),
  ssmp('Segment Anything Model', 'Zero-shot image segmentation via points, boxes, and masks.', 'Data', ['cv', 'sam'], 'segment-anything-model'),
  ssmp('DSPy', 'Declarative LM programs with auto-optimized prompts and RAG integration.', 'Data', ['dspy', 'llm'], 'dspy'),
  ssmp('arXiv', 'Search academic papers by keyword, author, category, or identifier.', 'Research', ['arxiv'], 'arxiv'),
  ssmp('Academic Researcher', 'Literature reviews, paper analysis, and scholarly writing assistance.', 'Research', ['academic'], 'academic-researcher'),
  ssmp('Data Analyst', 'SQL, pandas, and statistical analysis expertise for data exploration.', 'Data', ['sql', 'pandas'], 'data-analyst'),
  ssmp('Editor', 'Professional editing and proofreading for clarity, grammar, style.', 'Writing', ['editing'], 'editor'),
  ssmp('Fact Checker', 'Systematic fact verification and misinformation identification.', 'Research', ['verification'], 'fact-checker'),
  ssmp('Academic Paper Review', 'Structured reviews covering methodology, contribution, feedback.', 'Research', ['peer-review'], 'academic-paper-review'),
  ssmp('Systematic Literature Review', 'Survey and synthesis across academic papers with APA, IEEE, BibTeX.', 'Research', ['literature'], 'systematic-literature-review'),
  ssmp('Jupyter Notebook', 'Create, scaffold, and edit Jupyter notebooks with bundled templates.', 'Data', ['jupyter', 'python'], 'jupyter-notebook'),
  ssmp('Astropy', 'Core Python package for astronomy and astronomical research.', 'Research', ['astronomy'], 'astropy'),

  // ── Databases ────────────────────────────────────────────────────────────
  ssmp('JPA Patterns', 'Spring Boot JPA/Hibernate patterns for entities, relations, queries.', 'Data', ['java', 'jpa'], 'jpa-patterns-skill-md'),
  ssmp('Postgres Patterns', 'PostgreSQL patterns for query optimization, schema, indexing, security.', 'Data', ['postgres'], 'postgres-patterns-skill-md'),
  ssmp('Database Migrations', 'Schema changes, data migrations, rollbacks, zero-downtime deployments.', 'Data', ['migrations'], 'database-migrations-skill-md'),
  ssmp('ClickHouse Patterns', 'ClickHouse modes, query optimization, high-performance analytics.', 'Data', ['clickhouse'], 'clickhouse-io-skill-md'),
  ssmp('Drizzle ORM', 'Drizzle ORM schema and database guide for migrations and models.', 'Data', ['drizzle', 'ts'], 'drizzle-skill-md'),
  ssmp('Database Design', 'Schema design, indexing strategy, ORM selection, serverless databases.', 'Data', ['schema'], 'database-design-skill-md'),
  ssmp('SQL Optimization', 'Transform slow queries into fast operations via systematic indexing.', 'Data', ['sql'], 'sql-optimization-patterns-skill-md'),
  ssmp('PostgreSQL Optimization', 'Query tuning, indexing, performance analysis, production management.', 'Data', ['postgres'], 'postgresql-optimization-skill-md'),
  ssmp('Prisma Expert', 'Schema design, migrations, query optimization across databases.', 'Data', ['prisma'], 'prisma-expert-skill-md'),

  // ── Blockchain ───────────────────────────────────────────────────────────
  ssmp('DeFi AMM Security', 'Security checklist for Solidity AMM contracts, liquidity pools, swaps.', 'Blockchain', ['solidity', 'defi'], 'defi-amm-security'),
  ssmp('Node.js Keccak256', 'Prevent Ethereum hashing bugs in JavaScript/TypeScript development.', 'Blockchain', ['ethereum', 'nodejs'], 'nodejs-keccak256'),
  ssmp('CCXT C#', 'CCXT cryptocurrency exchange library for C# and .NET.', 'Blockchain', ['ccxt', 'dotnet'], 'ccxt-csharp'),
  ssmp('CCXT Go', 'Exchange library covering REST and WebSocket APIs for Go.', 'Blockchain', ['ccxt', 'go'], 'ccxt-go'),
  ssmp('CCXT PHP', 'CCXT cryptocurrency exchange library for PHP developers.', 'Blockchain', ['ccxt', 'php'], 'ccxt-php'),
  ssmp('CCXT Python', 'Exchange connectivity with sync/async support for Python projects.', 'Blockchain', ['ccxt', 'python'], 'ccxt-python'),
  ssmp('CCXT TypeScript', 'CCXT cryptocurrency exchange library for TypeScript and JavaScript.', 'Blockchain', ['ccxt', 'ts'], 'ccxt-typescript'),
  ssmp('Blockchain Developer', 'Build production-ready Web3 apps, smart contracts, and decentralized systems.', 'Blockchain', ['web3', 'solidity'], 'blockchain-developer'),
  ssmp('DeFi Protocol Templates', 'Production-ready templates for staking, AMMs, governance, and lending.', 'Blockchain', ['defi', 'solidity'], 'defi-protocol-templates'),
  ssmp('EmblemAI Crypto Wallet', 'Multi-blockchain wallet management across 7 networks.', 'Blockchain', ['solana', 'eth', 'btc'], 'emblemai-crypto-wallet'),
  ssmp('Lightning Architecture Review', 'Bitcoin Lightning Network protocol and Layer 2 scaling analysis.', 'Blockchain', ['bitcoin', 'lightning'], 'lightning-architecture-review'),
  ssmp('Lightning Factory Explainer', 'SuperScalar protocol and channel factory implementation guidance.', 'Blockchain', ['bitcoin', 'lightning'], 'lightning-factory-explainer'),
  ssmp('LLM App Patterns', 'Production patterns for building language model applications.', 'Coding', ['llm'], 'llm-app-patterns'),
  ssmp('NFT Standards', 'Master ERC-721 and ERC-1155 NFT standards.', 'Blockchain', ['nft', 'erc-721'], 'nft-standards'),
  ssmp('Security Auditor', 'DevSecOps and comprehensive cybersecurity audit expertise.', 'Testing', ['devsecops'], 'security-auditor'),
  ssmp('Solidity Security', 'Master smart contract security best practices.', 'Blockchain', ['solidity', 'security'], 'solidity-security'),
  ssmp('Telegram Mini App', 'Build Telegram Mini Apps (TWA) with native-like experience.', 'Coding', ['telegram', 'ton'], 'telegram-mini-app'),
  ssmp('Flutter Expert', 'Master Flutter development with Dart 3, advanced widgets, multi-platform.', 'Coding', ['flutter', 'dart'], 'flutter-expert'),

  // ── Lifestyle ────────────────────────────────────────────────────────────
  ssmp('Songwriting & AI Music', 'Songwriting craft and Suno AI music prompts.', 'Lifestyle', ['music', 'suno'], 'songwriting-and-ai-music'),
  ssmp('Obsidian', 'Read, search, create, and edit notes in the Obsidian vault.', 'Ops', ['obsidian', 'notes'], 'obsidian'),
  ssmp('Brand Guidelines', 'Apply visual design standards and brand identity to artifacts.', 'Design', ['brand'], 'brand-guidelines'),
  ssmp('Brand Writer', 'Write clear, developer-first copy for Zed — leading with facts.', 'Writing', ['copy'], 'brand-writer'),
  ssmp('Writing Beats', 'Shape content as narrative journey with choose-your-own-adventure structure.', 'Writing', ['storytelling'], 'writing-beats'),
  ssmp('Axiom', 'First-principles assumption auditor; classifies and rebuilds conclusions.', 'Lifestyle', ['critical-thinking'], 'axiom'),
  ssmp('Beautiful Prose', 'Hard-edged writing style contract for timeless, forceful English prose.', 'Writing', ['style'], 'beautiful-prose'),
  ssmp('Claude Ally Health', 'Medical information analysis, symptom tracking, wellness guidance.', 'Medical', ['health'], 'claude-ally-health'),
  ssmp('Explain Like Socrates', 'Explain concepts using Socratic-style dialogue and questioning.', 'Lifestyle', ['education'], 'explain-like-socrates'),
  ssmp('Family Health Analyzer', 'Analyze family health history and genetic risk assessment.', 'Medical', ['health'], 'family-health-analyzer'),
  ssmp('HR Pro', 'Professional, ethical HR partner for hiring and onboarding/offboarding.', 'Business', ['hr'], 'hr-pro'),
  ssmp('Mental Health Analyzer', 'Analyze psychological patterns and provide personalized wellness guidance.', 'Lifestyle', ['mental-health'], 'mental-health-analyzer'),
  ssmp('Satori', 'Clinically informed wisdom companion blending psychology and philosophy.', 'Lifestyle', ['wellness'], 'satori'),
  ssmp('TCM Constitution Analyzer', 'Traditional Chinese Medicine constitution analysis and wellness.', 'Medical', ['tcm'], 'tcm-constitution-analyzer'),
  ssmp('Theme Factory', 'Curated collection of professional font and color themes for artifacts.', 'Design', ['themes'], 'theme-factory'),
  ssmp('WellAlly Tech', 'Integrate multiple digital health data sources with KB access.', 'Medical', ['health-data'], 'wellally-tech'),
  ssmp('SEO Fundamentals', 'Core principles of SEO including E-E-A-T and Core Web Vitals.', 'Growth', ['seo'], 'seo-fundamentals'),
  ssmp('Image Generation', 'Generate and visualize images including characters and scenes.', 'Design', ['image-gen'], 'image-generation'),
];

function csi(name: string, tagline: string, category: string, slug: string): SkillExample {
  return {
    name,
    tagline,
    category,
    tools: ['Markdown'],
    kb: 'claudeskills.info',
    price: 0,
    pack: 'claudeskills',
    slug,
  };
}

export const CLAUDESKILLS_SKILLS: SkillExample[] = [
  csi('ABM Outbound', 'Multi-channel ABM automation that turns LinkedIn URLs into coordinated outbound campaigns.', 'Sales', 'abm-outbound'),
  csi('Ad Copywriter', 'Ad copywriter for feed ads, search ads, social ads, A/B testing, ROI calculator, and platform-specific copy.', 'Growth', 'ad-copywriter'),
  csi('Agentic Actions Auditor', 'Audits GitHub Actions workflows for security vulnerabilities in AI agent integrations like Claude Code, Gemini CLI, and Codex.', 'Testing', 'agentic-actions-auditor'),
  csi('AI Image Generation & Editor', 'Generate images from text with multi-provider routing — Nanobanana 2, Seedream 5.0, GPT Image, and local ComfyUI workflows.', 'Design', 'ai-image-generation--editor--nanobanana-gpt-image-comfyui'),
  csi('Algorithmic Art (CSI)', 'Generative art in p5.js with seeded randomness and interactive parameter exploration.', 'Design', 'algorithmic-art'),
  csi('Anthropic Official Skills', '16 official skills from Anthropic — frontend design, PDF, DOCX, XLSX, MCP builder, and more.', 'Coding', 'anthropic-official'),
  csi('Article Illustrator', 'Add high-quality illustrations to articles or blog posts.', 'Design', 'article-illustrator'),
  csi('Artifacts Builder', 'Build complex claude.ai HTML artifacts using React, Tailwind CSS, and shadcn/ui components.', 'Coding', 'artifacts-builder'),
  csi('GitHub Copilot Skills', '324 official GitHub Copilot plugin skills across Azure, .NET, Docker, and more.', 'Coding', 'awesome-copilot-skills'),
  csi('Azure RM Playwright (.NET)', 'Azure Resource Manager SDK for Microsoft Playwright Testing in .NET.', 'DevOps', 'azure-resource-manager-playwright-dotnet'),
  csi('Better Genshin Impact', 'BetterGI — C# automation toolkit for Genshin Impact (pickups, fishing, mining, daily routines).', 'Lifestyle', 'better-genshin-impact'),
  csi('BotEmail.ai', 'Get an email address without a human. Use for testing signup flows, verification codes, and email automation.', 'Writing', 'botemailai---free-bot-email'),
  csi('Brand Guidelines (CSI)', "Apply Anthropic's official brand colors and typography to artifacts.", 'Design', 'brand-guidelines'),
  csi('Canvas Design (CSI)', 'Create visual art in .png and .pdf using composition and design philosophy.', 'Design', 'canvas-design'),
  csi('CodeQL', "Scan a codebase for security vulnerabilities using CodeQL's interprocedural data flow and taint tracking.", 'Testing', 'codeql'),
  csi('Constant Time Analysis', 'Detect timing side-channel vulnerabilities in cryptographic code.', 'Testing', 'constant-time-analysis'),
  csi('Content Research Writer', 'Write high-quality content by conducting research, adding citations, and providing review feedback.', 'Writing', 'content-research-writer'),
  csi('Context Engineering', 'Core context engineering techniques for AI agents.', 'Coding', 'context-engineering'),
  csi('Context Engineering Guide', 'Tutorial on attention mechanics, progressive disclosure, context budget management, and quality vs quantity.', 'Coding', 'context-engineering-neolab'),
  csi('Crypto Wallet', 'Discover supported cryptocurrencies, generate deposit addresses, and withdraw crypto to external wallets.', 'Blockchain', 'crypto-wallet'),
  csi('Debug Buttercup', 'Debug the Buttercup CRS (Cyber Reasoning System) running on Kubernetes.', 'Testing', 'debug-buttercup'),
  csi('Differential Review', 'Security-focused differential review of code changes (PRs, commits, diffs).', 'Coding', 'differential-review'),
  csi('ERC-8004 Agent Discovery', 'Search 43k+ AI agents registered via ERC-8004. Find agents by skill, chain, or reputation.', 'Blockchain', 'erc-8004-agent-discovery'),
  csi('Everything Claude Code', 'Claude Code optimization system with 86+ skills, rules, hooks, and agent configurations.', 'Coding', 'everything-claude-code'),
  csi('Excel / XLSX (CSI)', 'Create, inspect, and edit Excel workbooks with reliable formulas, dates, types, formatting, and recalculation.', 'Data', 'excel--xlsx'),
  csi('FFmpeg Video Editor', 'Generate FFmpeg commands from natural-language editing requests — cut, trim, convert, compress, extract audio.', 'Design', 'ffmpeg-video-editor'),
  csi('Figma', 'Figma design analysis and asset export — extract design data, export assets, audit components.', 'Design', 'figma'),
  csi('GSD Claw', 'Spec-driven development with built-in verification for substantial projects.', 'DevOps', 'gsd-claw'),
  csi('Intelligence Ingestion', 'Analyze and evaluate URLs, articles, tweets, and external sources for strategic value.', 'Research', 'intelligence-ingestion'),
  csi('Internal Comms (CSI)', 'Write internal communications like status reports, newsletters, and FAQs.', 'Writing', 'internal-comms'),
  csi('Intune Graph API', 'Comprehensive skill to manage Microsoft Intune via the Graph API.', 'DevOps', 'intune-graph-api--complete-management'),
  csi('LangSmith Fetch', 'Debug LangChain and LangGraph agents by fetching execution traces from LangSmith Studio.', 'Data', 'langsmith-fetch'),
  csi('MBTI Persona Stylizer', 'Dynamic communication style and perspective configurator based on the 16 MBTI personality types.', 'Lifestyle', 'mbti-16-personality-stylized-persona-skill'),
  csi('MCP Builder (CSI)', 'Guide for creating high-quality MCP servers to integrate external APIs and services.', 'Coding', 'mcp-builder'),
  csi('Microsoft Skills', '333 skills across Azure, .NET, and AI Foundry — the largest enterprise skills collection.', 'Coding', 'microsoft-skills'),
  csi('Multi-Agent Patterns', 'Reference for multi-agent architecture patterns — Supervisor/Orchestrator, Peer-to-Peer/Swarm, Hierarchical.', 'Coding', 'multi-agent-patterns'),
  csi('OpenAI Official Skills', '37 official skills from OpenAI for Codex CLI and multi-agent development.', 'Coding', 'openai-official'),
  csi('PDF Processor (CSI)', 'PDF manipulation toolkit — extract text and tables, create new PDFs, merge and split documents.', 'Ops', 'pdf-skill'),
  csi('Persona Channel Builder', 'Design and launch an autonomous AI-managed Telegram channel from a persona interview.', 'Growth', 'persona-channel-builder'),
  csi('Playwright Browser Automation', 'General-purpose browser automation with Playwright — pages, forms, responsive design, UX validation.', 'Testing', 'playwright-skill'),
  csi('Prompt Engineering', 'Well-known prompt engineering techniques and patterns, including Anthropic best practices and agent principles.', 'Coding', 'prompt-engineering'),
  csi('Semgrep', 'Run Semgrep static analysis on a codebase using parallel subagents.', 'Testing', 'semgrep'),
  csi('Semgrep Rule Creator', 'Create custom Semgrep rules for security vulnerabilities, bug patterns, and code patterns.', 'Testing', 'semgrep-rule-creator'),
  csi('Semgrep Rule Variant Creator', 'Create language variants of existing Semgrep rules. Use when porting a rule to new target languages.', 'Testing', 'semgrep-rule-variant-creator'),
  csi('Sharp Edges', 'Identifies error-prone APIs, dangerous configurations, and footgun designs that enable security mistakes.', 'Testing', 'sharp-edges'),
  csi('Skill Seekers', 'Automatically convert any documentation website into a Claude AI skill in minutes.', 'Ops', 'skill-seekers'),
  csi('Spec-to-Code Compliance', 'Verify code implements exactly what documentation specifies — built for blockchain audits.', 'Testing', 'spec-to-code-compliance'),
  csi('Superpowers', 'Comprehensive workflow system for Claude with 20 proven development techniques.', 'Coding', 'superpowers'),
  csi('Test Generator', 'Automated test generator — unit, integration, e2e, mocks, fixtures, coverage, edge cases.', 'Testing', 'test-generator'),
  csi('Variant Analysis', 'Find similar vulnerabilities and bugs across codebases using pattern-based analysis.', 'Testing', 'variant-analysis'),
  csi('Vercel React Best Practices', 'React and Next.js performance optimization guidelines from Vercel Engineering.', 'Coding', 'vercel-react-best-practices'),
  csi('Vercel Skills', '8 official Vercel skills for Next.js, React, and edge deployment.', 'Coding', 'vercel-skills'),
  csi('WordPress Skills', '26 official WordPress and Automattic skills for blocks, themes, and plugin development.', 'Coding', 'wordpress-skills'),
];

export const SKILL_EXAMPLES: SkillExample[] = [
  ...MEDICAL_SKILLS,
  ...ANTHROPIC_SKILLS,
  ...SKILLSMP_SKILLS,
  ...CLAUDESKILLS_SKILLS,
];

export const POPULAR_SKILL_NAMES: readonly string[] = [
  'Coding Agent',
  'Claude API',
  'Frontend Design',
  'Skill Creator',
  'MCP Builder',
  'Deep Research',
  'PDF Toolkit',
  'Brand Voice',
  'Notion',
  'GitHub',
  'Content Engine',
  'DSPy',
];
